name: Deploy to Railway

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Login Railway & Deploy
        run: railway up --service kiyxc
        env:
          RAILWAY_TOKEN: 94b46a96-7c44-45e4-bdfc-1179dca0e705
