name: Deploy ke Railway

on:
  push:
    branches:
      - main # ganti kalau branch kamu beda

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Railway CLI
        run: npm install -g railway

      - name: Railway Login
        run: railway login --token 94b46a96-7c44-45e4-bdfc-1179dca0e705

      - name: Link Project
        run: railway link

      - name: Deploy ke Railway
        run: railway up
