name: Deploy to Railway

on:
  push:
    branches:
      - main # ganti kalau kamu pakai branch lain

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Link Railway Project
        run: railway link 919caca5-e737-47bd-aa8c-3074077351cf
        env:
          RAILWAY_TOKEN: 94b46a96-7c44-45e4-bdfc-1179dca0e705

      - name: Deploy to Railway
        run: railway up
        env:
          RAILWAY_TOKEN: 94b46a96-7c44-45e4-bdfc-1179dca0e705
