name: Deploy ke Railway

on:
  push:
    branches:
      - main # Ganti jika kamu pakai branch lain

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Railway CLI (baru)
        run: npm install -g @railway/cli

      - name: Login ke Railway
        run: railway login --token 94b46a96-7c44-45e4-bdfc-1179dca0e705

      - name: Link ke Project Railway
        run: railway link

      - name: Deploy ke Railway
        run: railway up
